### ISSUE TITLE
My renders are bugged

### ISSUE THREAD

**Issue by GentlemanMC** [Bixilon/Minosoft#13] opened 2023-05-22 16:32 UTC
I have a AMD radeon hd 7650m GPU (it supports up to OpenGL version 4.4) but the rendering is quite buggy

here is a screenshot of how it's looking
![image](https://github.com/Bixilon/Minosoft/assets/76640636/ea0af95a-bd0f-46f0-b963-f933ea313ae3)

**Comment by Bixilon** [comment] 2023-05-22 16:41
What are your coordinates (`F3`)?

Might be a duplicate of https://gitlab.bixilon.de/bixilon/minosoft/-/issues/108

**Comment by GentlemanMC** [comment] 2023-05-22 17:53
Im not saying my exact coords but im more than 100k away from x0 z0

**Comment by GentlemanMC** [comment] 2023-05-22 17:55
Oh also when i move around it bugs harder

**Comment by Bixilon** [comment] 2023-05-22 17:59
Yep, I noticed that a couple of months ago.

When the coordinates are too high, the values are not precise enough. I don't know how to solve it easily (without reducing performance).

Maybe adding ` precision highp float;` after the `#version` line in the world shaders could make it better (https://github.com/Bixilon/Minosoft/blob/master/src/main/resources/assets/minosoft/rendering/shader/world/world.fsh and https://github.com/Bixilon/Minosoft/blob/master/src/main/resources/assets/minosoft/rendering/shader/world/world.vsh)

**Comment by Bixilon** [comment] 2023-05-23 19:03
Should be fixed, can you check https://gitlab.bixilon.de/bixilon/minosoft/-/merge_requests/86? Maybe you see something that I haven't thought of yet.

**Comment by GentlemanMC** [comment] 2023-05-25 11:07
do i have to build it from the src or is there something like github actions runner in gitlab (i've never used gitlab before sorry)

**Comment by Bixilon** [comment] 2023-05-25 18:01
Should be fixed now!

**Closed by Bixilon** 2023-05-25 18:01 UTC
